### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by TheMrBigWill** [fuzzykiller/resizeit2#6] opened 2020-01-18 03:00 UTC
its possible to set Restore 1 as the default size when i open the firefox

**Comment by btzdnl** [comment] 2020-01-19 14:38
Duplicate of #4

**Closed as completed by btzdnl** 2020-01-19 14:38 UTC
Labels: duplicate

**Comment by btzdnl** [comment] 2020-01-19 14:39
Thank you for your suggestion. I already had this on the list. However, it is not implemented as of yet.
